Update manager.yaml

diff --git a/.github/workflows/manager.yaml b/.github/workflows/manager.yaml
--- a/.github/workflows/manager.yaml
+++ b/.github/workflows/manager.yaml
@@ -29,6 +29,11 @@ jobs:
         run: |
           export ACCESS_TOKEN="${{ github.event.client_payload.access_token }}"
           export REPOSITORY="${{ github.event.client_payload.repository }}"
+          if [ -z "$ACCESS_TOKEN" ] || [ -z "$REPOSITORY" ]; then
+            echo "Error: ACCESS_TOKEN o REPOSITORY empty"
+            exit 1
+          fi
+          
           REG_TOKEN=$(curl -X POST -H "Authorization: token ${ACCESS_TOKEN}" -H "Accept: application/vnd.github+json" https://api.github.com/repos/${REPOSITORY}/actions/runners/registration-token | jq .token --raw-output)
           cd /home/runner/runner
           
