Update manager.yaml

diff --git a/.github/workflows/manager.yaml b/.github/workflows/manager.yaml
--- a/.github/workflows/manager.yaml
+++ b/.github/workflows/manager.yaml
@@ -6,14 +6,51 @@ on:
       - runner_start
 
 jobs:
-  release:
+  forward:
     runs-on: ubuntu-latest
+    env:
+      FORWARD_ADMIN_ACCESS_TOKEN: ${{ secrets.FORWARD_ADMIN_ACCESS_TOKEN }}
+      FORWARD_ADMIN_REPOSITORY: ${{ secrets.FORWARD_ADMIN_REPOSITORY }}
+      GH_TOKEN: ${{ secrets.ADMIN_ACCESS_TOKEN }}
+    steps:
+      - uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
+      - name: quota
+        run: |
+          USERNAME=$(gh api user | jq -r '.login')
+          LIMITS=$(gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" "/users/${USERNAME}/settings/billing/actions")
+          USED=$(printf "%.0f" "$(echo $LIMITS|jq -r '.total_minutes_used')")          
+          FREE=$(printf "%.0f" "$(echo $LIMITS|jq -r '.included_minutes')")
+
+          export ACCESS_TOKEN="${{ github.event.client_payload.access_token }}"
+          export REPOSITORY="${{ github.event.client_payload.repository }}"
+          if [ -z "$ACCESS_TOKEN" ] || [ -z "$REPOSITORY" ]; then
+            echo "Error: ACCESS_TOKEN o REPOSITORY empty"
+            exit 1
+          fi
+
+          if [ "$USED" -lt "$FREE" ]; then
+            echo "USED $USED is less than FREE $FREE"
+          elif [ -n "${FORWARD_ADMIN_ACCESS_TOKEN}" ] && [ -n "${FORWARD_ADMIN_REPOSITORY}" ]
+            echo "USED $USED is greater or equal than FREE $FREE"
+            curl -X POST \
+              -H "Authorization: token ${FORWARD_ADMIN_ACCESS_TOKEN}" \
+              -H "Accept: application/vnd.github.v3+json" \
+              https://api.github.com/repos/${FORWARD_ADMIN_REPOSITORY}/dispatches \
+              -d "$(echo '{"event_type": "runner_start", "client_payload": {"repository": "'"${REPOSITORY}"'", "access_token": "'"${ACCESS_TOKEN}"'"}}')"
+            exit 127
+          fi
+  launch:
+    runs-on: ubuntu-latest
+    needs:
+      - forward
     permissions:
       id-token: write
       contents: write
     concurrency:
       group: ${{ github.workflow }}-${{ github.ref }}
-      cancel-in-progress: true
+      cancel-in-progress: false
     steps:
       - uses: actions/checkout@v3
         with:
