reorder jobs

diff --git a/.github/workflows/manager.yaml b/.github/workflows/manager.yaml
--- a/.github/workflows/manager.yaml
+++ b/.github/workflows/manager.yaml
@@ -8,49 +8,6 @@ on:
 jobs:
   forward:
     runs-on: ubuntu-latest
-    env:
-      FORWARD_ADMIN_ACCESS_TOKEN: ${{ secrets.FORWARD_ADMIN_ACCESS_TOKEN }}
-      FORWARD_ADMIN_REPOSITORY: ${{ secrets.FORWARD_ADMIN_REPOSITORY }}
-      GH_TOKEN: ${{ secrets.ADMIN_ACCESS_TOKEN }}
-    steps:
-      - uses: actions/checkout@v3
-        with:
-          fetch-depth: 0
-      - name: quota
-        run: |
-          USERNAME=$(gh api user | jq -r '.login')
-          LIMITS=$(gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" "/users/${USERNAME}/settings/billing/actions")
-          USED=$(printf "%.0f" "$(echo $LIMITS|jq -r '.total_minutes_used')")          
-          FREE=$(printf "%.0f" "$(echo $LIMITS|jq -r '.included_minutes')")
-
-          export ACCESS_TOKEN="${{ github.event.client_payload.access_token }}"
-          export REPOSITORY="${{ github.event.client_payload.repository }}"
-          if [ -z "$ACCESS_TOKEN" ] || [ -z "$REPOSITORY" ]; then
-            echo "Error: ACCESS_TOKEN o REPOSITORY empty"
-            exit 1
-          fi
-
-          if [ "$USED" -lt "$FREE" ]; then
-            echo "USED $USED is less than FREE $FREE"
-          elif [ -n "${FORWARD_ADMIN_ACCESS_TOKEN}" ] && [ -n "${FORWARD_ADMIN_REPOSITORY}" ]; then
-            echo "USED $USED is greater or equal than FREE $FREE"
-            curl -X POST \
-              -H "Authorization: token ${FORWARD_ADMIN_ACCESS_TOKEN}" \
-              -H "Accept: application/vnd.github.v3+json" \
-              https://api.github.com/repos/${FORWARD_ADMIN_REPOSITORY}/dispatches \
-              -d "$(echo '{"event_type": "runner_start", "client_payload": {"repository": "'"${REPOSITORY}"'", "access_token": "'"${ACCESS_TOKEN}"'"}}')"
-            exit 127
-          fi
-  launch:
-    runs-on: ubuntu-latest
-    needs:
-      - forward
-    permissions:
-      id-token: write
-      contents: write
-    concurrency:
-      group: ${{ github.workflow }}-${{ github.ref }}
-      cancel-in-progress: false
     steps:
       - uses: actions/checkout@v3
         with:
@@ -78,15 +35,62 @@ jobs:
           Signed-By: /usr/share/keyrings/gopass-archive-keyring.gpg
           EOF
           sudo apt update && sudo apt install -qy gopass gopass-archive-keyring
-          
+
           git clone -b master ${GOPASS_STORE} ~/.password-store
-          
+
           cd ~/.password-store
-          
+
           git config user.email "bot@github-action.com"
           git config user.name "Bot Action"
-          
+
           gopass --yes --nosync sync
+      - name: quota
+        run: |
+          GH_TOKEN=$(gopass show --password -n -f github/action/runner/config/${GITHUB_REPOSITORY}/admin/access_token 2>/dev/null)
+          FORWARD_ADMIN_ACCESS_TOKEN=$(gopass show --password -n -f github/action/runner/config/${GITHUB_REPOSITORY}/forward/access_token 2>/dev/null)
+          FORWARD_ADMIN_REPOSITORY=$(gopass show --password -n -f github/action/runner/config/${GITHUB_REPOSITORY}/forward/repository 2>/dev/null)
+          USERNAME=$(gh api user | jq -r '.login')
+          LIMITS=$(gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" "/users/${USERNAME}/settings/billing/actions")
+          USED=$(printf "%.0f" "$(echo $LIMITS|jq -r '.total_minutes_used')")          
+          FREE=$(printf "%.0f" "$(echo $LIMITS|jq -r '.included_minutes')")
+
+          export ACCESS_TOKEN="${{ github.event.client_payload.access_token }}"
+          export REPOSITORY="${{ github.event.client_payload.repository }}"
+          if [ -z "$ACCESS_TOKEN" ] || [ -z "$REPOSITORY" ]; then
+            echo "Error: ACCESS_TOKEN o REPOSITORY empty"
+            exit 1
+          fi
+
+          if [ "$USED" -lt "$FREE" ]; then
+            echo "USED $USED is less than FREE $FREE"
+          elif [ -n "${FORWARD_ADMIN_ACCESS_TOKEN}" ] && [ -n "${FORWARD_ADMIN_REPOSITORY}" ]; then
+            echo "USED $USED is greater or equal than FREE $FREE"
+            curl -X POST \
+              -H "Authorization: token ${FORWARD_ADMIN_ACCESS_TOKEN}" \
+              -H "Accept: application/vnd.github.v3+json" \
+              https://api.github.com/repos/${FORWARD_ADMIN_REPOSITORY}/dispatches \
+              -d "$(echo '{"event_type": "runner_start", "client_payload": {"repository": "'"${REPOSITORY}"'", "access_token": "'"${ACCESS_TOKEN}"'"}}')"
+            exit 127
+          fi
+      - name: teardown
+        run: |
+          rm -rf ~/.password-store
+          gpgconf --kill gpg-agent" > /dev/null 2>&1
+  launch:
+    runs-on: ubuntu-latest
+    needs:
+      - forward
+    permissions:
+      id-token: write
+      contents: write
+    concurrency:
+      group: ${{ github.workflow }}-${{ github.ref }}
+      cancel-in-progress: false
+    steps:
+      - uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
+
       - name: connect
         run: |
           mkdir -p $HOME/runner
